# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  email_provider_username: <%= ENV["SENDGRID_USERNAME"] %>
  email_provider_password: <%= ENV["SENDGRID_PASSWORD"] %>
  domain_name: example.com
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %>
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %>
  stripe_api_key: <%= ENV["STRIPE_API_KEY"] %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %>
  product_title: <%= ENV["PRODUCT_TITLE"] %>
  product_price: <%= ENV["PRODUCT_PRICE"] %>
  secret_key_base: 7e821f25e756b8ba8db27725d6464123c70b03a622291b89c0ff1def7a9c7ba9777a9d1714653c6140e6ce6f9c23317b88a2bd91b9cc3f65716b9c2fbe39e571

test:
  domain_name: example.com 
  secret_key_base: d5c75e1fff9cf571e70ce7d291a3c0228f84594a4c326921ec22351140b03f6323c9e6543c6b589b2418f4969690cf82b4ad734963d7ba514d946ba9ee2ddf5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  email_provider_username: <%= ENV["SENDGRID_USERNAME"] %>
  email_provider_password: <%= ENV["SENDGRID_PASSWORD"] %> 
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  mailchimp_api_key: <%= ENV["MAILCHIMP_API_KEY"] %> 
  mailchimp_list_id: <%= ENV["MAILCHIMP_LIST_ID"] %> 
  stripe_api_key: <%= ENV["STRIPE_API_KEY"] %> 
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %> 
  product_title: <%= ENV["PRODUCT_TITLE"] %> 
  product_price: <%= ENV["PRODUCT_PRICE"] %> 
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
